image: Visual Studio 2019
branches:
  only:
  - /\d*\.\d*\.\d*/

only_commits:
  author: /Automation Agent/

init:
  - ps: |
        $valid = $env:APPVEYOR_FORCED_BUILD -and $env:APPVEYOR_REPO_COMMIT_AUTHOR -like "*Automation Agent*"
        if (!$valid)
        {
            throw "This build environment is only intended for externally configured automated processes."
        }
        
# disable build and test pahses
build: off
test: off