image: Visual Studio 2019
branches:
  only:
  - /\d*\.\d*\.\d*/

only_commits:
  author: /GitHub Action Automation/

init:
  - ps: |
        $first = $env:APPVEYOR_FORCED_BUILD
        $second = $env:APPVEYOR_REPO_COMMIT_AUTHOR -contains "*Automation Agent*"
        $valid = $first -and $second
        $first
        $second
        $valid
        if (!$valid)
        {
            Get-ChildItem Env:
            throw "This build environment is only intended for externally configured automated processes."
        }
        
# disable build and test pahses
build: off
test: off