image: Visual Studio 2019
branches:
  only:
  - /\d*\.\d*\.\d*/

only_commits:
  author: /*GitHub Action Automation*/

init:
  - ps: |
        if (!$env:APPVEYOR_FORCED_BUILD)
        {
            throw "This build environment is only intended for externally configured automated processes."
        }
        
# disable build and test pahses
build: off
test: off