image: Visual Studio 2019
branches:
  only:
  - master

# skip_commits:
#  author: /ExtendedXmlSerializer Automation*/
  # files:
  #  - '.github\**\*.*'

init:
  - ps: |
        Write-Host "HELLO WORLD!"
        Get-ChildItem Env: # | Where-Object { $_.Name.StartsWith( "APPVEYOR" ) }
        
# disable build and test pahses
build: off
test: off