name: CHANGELOG, Dawg!

on: [push]

jobs:
  generate_and_store:
    runs-on: ubuntu-latest
    steps:
    - id: generate
      name: Generate CHANGELOG, dawg!
      uses: dragonspark/action-changelog-dawg@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload CHANGELOG
      uses: actions/upload-artifact@v1
      with:
        name: store
        path: '${{ steps.generate.outputs.filename }}'
  
  load_and_commit:
    runs-on: ubuntu-latest
    needs: [generate_and_store]    
    steps:
      - name: List contents Before Checkout
        run: |
             Get-ChildItem .
        shell: pwsh
      - uses: actions/checkout@master
        with:
          repository: https://github.com/Mike-EEE/action-jackson.wiki.git
      - name: List contents After Checkout
        run: |
             Get-ChildItem .
        shell: pwsh
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: store
          path: ./
      - name: after
        run: |
             Write-Host "After: $PWD"
             Get-ChildItem .
             # Set-Content CHANGELOG.md $env:CHANGELOG           
             # Write-Host "After: $PWD"
             # Get-ChildItem .
        shell: pwsh
###
