name: CHANGELOG, Dawg!

on: [push]

env:
  DEPLOY_USER: "GitHub Action Automation Identity: Action Jackson"
  DEPLOY_EMAIL: mike-eee@noreply.users.github.com

jobs:
  generate_and_store:
    runs-on: ubuntu-latest
    steps:
    - id: generate
      name: Generate CHANGELOG, dawg!
      uses: dragonspark/action-changelog-dawg@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload CHANGELOG
      uses: actions/upload-artifact@v1
      with:
        name: store
        path: '${{ steps.generate.outputs.filename }}'
  
  push_to_wiki:
    runs-on: ubuntu-latest
    needs: [generate_and_store]    
    steps:
      - name: List contents Before Checkout
        run: |
             Get-ChildItem .
        shell: pwsh
      - uses: actions/checkout@master
        with:
          repository: Mike-EEE/action-jackson.wiki
          ref: refs/heads/master
          path: ./action-jackson
      - name: List contents After Checkout
        run: |
             Get-ChildItem .
        shell: pwsh
      - name: Download the CHANGELOG, dawg!
        uses: actions/download-artifact@v1
        with:
          name: store
          path: ./
      - name: Add and Commit
        run: |
             git config user.email $env:DEPLOY_EMAIL
             git config user.name $env:DEPLOY_USER
             git add -A 2>&1
             git commit -m "Adding CHANGELOG.md" -a
        shell: pwsh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: Mike-EEE/action-jackson.wiki
          # github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Workspace Status
        run: |
             Write-Host "After: $PWD"
             Get-ChildItem .
             git status -sb
        shell: pwsh
###
