name: CHANGELOG, Dawg!

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@master
#    - name: List contents BEFORE
#      run: |
#           Get-ChildItem .
#           Write-Host "BEFORE! $PWD"
#      shell: pwsh
    - name: Generate a CHANGELOG, dawg!
      uses: dragonspark/action-changelog-dawg@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: List contents AFTER
#      run: |
#           Get-ChildItem .
#           Write-Host "AFTER! $PWD"
#      shell: pwsh
    
###
