name: CHANGELOG, Dawg!

on: [push]

jobs:
  generate and store:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@master
#    - name: List contents BEFORE
#      run: |
#           Get-ChildItem .
#           Write-Host "BEFORE! $PWD"
#      shell: pwsh
    - name: generate
      uses: dragonspark/action-changelog-dawg@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload CHANGELOG
      uses: actions/upload-artifact@v1
      with:
        name: store
        path: ${{ steps.generate.inputs.filename }}        
  
  load and commit:
    runs-on: ubuntu-latest
    steps:
       - name: Download math result for job 1
         uses: actions/download-artifact@v1
         with:
           name: store
       - name: after
         run: |
              Write-Host "After: $PWD"
              Get-ChildItem .
              # Set-Content CHANGELOG.md $env:CHANGELOG           
              # Write-Host "After: $PWD"
              # Get-ChildItem .
         shell: pwsh
###
