name: CHANGELOG, Dawg! Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Generate a CHANGELOG, dawg!
      uses: dragonspark/action-changelog-dawg@master
### 
