name: CHANGELOG, Dawg!

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@master
#    - name: List contents BEFORE
#      run: |
#           Get-ChildItem .
#           Write-Host "BEFORE! $PWD"
#      shell: pwsh
    - name: generate
      uses: dragonspark/action-changelog-dawg@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Results
      env:
        CHANGELOG: ${{ steps.generate.outputs.result }}
      run: |
           Write-Host "Before: $PWD"
           Get-ChildItem .
           Set-Content CHANGELOG.md $env:CHANGELOG           
           Write-Host "After: $PWD"
           Get-ChildItem .
      shell: pwsh    
###
