name: Temp test

on: [push]

env:
  DEPLOY_USER: "Mike-EEE's GitHub Action Automation Agent"
  DEPLOY_EMAIL: "Mike-EEE@users.noreply.github.com"
  DEPLOY_SLUG: action-jackson
  DEPLOY_COMMIT_MESSAGE: Adding CHANGELOG.md

jobs:
  load_and_push_to_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}.wiki
          ref: refs/heads/master
          path: ./${{ github.event.repository.name }}
      - name: Add and Commit
        run: |
             git config user.email $env:DEPLOY_EMAIL
             git config user.name $env:DEPLOY_USER
             git add -A 2>&1
             git commit -m "${DEPLOY_COMMIT_MESSAGE}"
        shell: pwsh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ github.repository }}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
