name: Publish Release Build

on:
  release:
    types: [published]

env:
  DEPLOY_USER: "Mike-EEE's GitHub Action Automation Agent"
  DEPLOY_EMAIL: "Mike-EEE@users.noreply.github.com"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Initiate Build Process
      run: |
           $headers = @{
             "Authorization" = "Bearer ${{ secrets.API_APPVEYOR_TOKEN }}"
             "Content-type" = "application/json"
           }

           $body = @{
               accountName="ExtendedXmlSerializer"
               projectSlug="action-jackson"
               branch="master"
               commitId="${{ github.event.release.tag_name }}"
               environmentVariables = @{
                 APPVEYOR_REPO_COMMIT_AUTHOR = $env:DEPLOY_USER
                 APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL = $env:DEPLOY_EMAIL
               }
           }
           $body = $body | ConvertTo-Json

           Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers  -Body $body -Method POST
      shell: pwsh
