name: Manual Build Trigger

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v1
    # - name: Run a one-line script
    #  run: echo Hello, world!
    - name: Run a multi-line script
      run: |
           $headers = @{
             "Authorization" = "Bearer ${{ secrets.API_APPVEYOR_TOKEN }}"
             "Content-type" = "application/json"
           }

           $body = @{
               accountName="ExtendedXmlSerializer"
               projectSlug="action-jackson"
               branch="master"
               commitId="v2FRIST"
               authorName="asdf1"
               authorUsername="asdf2"
               committerName="asdf3"
               committerUsername="asdf4"
           }
           $body = $body | ConvertTo-Json

           Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers  -Body $body -Method POST
      shell: pwsh
